### ISSUE TITLE
skipTo() fails on Chrome

### ISSUE THREAD

**Issue by jwoldan** [kolber/audiojs#61] opened 2012-04-04 17:41 UTC
Current version of Chrome (18.0.1025.142).  The playhead is not reset when `skipTo()` is called.  Directly setting the element's currentTime attribute fails as well.  Is this a bug in Chrome?  (Note: in my testing, there are multiple instances of the player on the page, and it works fine in Safari).

Note: I'm using `skipTo()` to return the playhead to the start of the track when it finishes playing.  As a workaround, if `skipTo()` fails (determined by checking if `audiojs.element.ended` is true) I reload the track (` audiojs.load(audiojs.mp3)`).

**Comment by Zetaphor** [comment] 2016-01-29 02:49
Unable to reproduce in the latest Chrome release on Android and desktop. Closing unless this is still an issue

**Closed by Zetaphor** 2016-01-29 02:49 UTC
