### ISSUE TITLE
Drastic Firefox slowdown on audio load

### ISSUE THREAD

**Issue by martinchristov** [kolber/audiojs#54] opened 2012-01-17 12:58 UTC
Hi there!

Although it's a great audio player script I had some issues with it, the main of which is a drastic Firefox slowdown while a song is being loaded.
After the song finishes loading everything goes back to normal.
And by a drastic slowdown I mean even scrolling the page takes a few seconds to update.

I am testing this on various machines with FF 8 & 9.

Chrome & IE have no such issues.
WTF happened with FF lately?! Even IE is at least a few times faster.

Do u know anything about this issue ?

**Comment by Zetaphor** [comment] 2016-01-28 18:46
Unable to reproduce, appears to be fixed in latest browser releases

**Closed by Zetaphor** 2016-01-28 18:46 UTC
