### ISSUE TITLE
Android problem - needs three Taps to play!

### ISSUE THREAD

**Issue by tlimited** [kolber/audiojs#177] opened 2014-07-14 11:51 UTC
On Android the audio player needs three taps on Play-button to play the audio. 
How can this be fixed? A quick workaround is also appreciated as I'm close to a deadline.

To repro:
1. go to http://kolber.github.io/audiojs/ on a android device, I tested with a Sony Xperia Z1 running Android 4.4.2. 
2. expect the play/pause button to be in play state, but is actually in loading state
3. clicking play makes the button go into play state
4. clicking button again sets the button into loading state
5. clicking button again sets the button into playing state, and this time actually playing the audio

**Comment by Zetaphor** [comment] 2016-01-28 18:56
Unable to reproduce in latest browser releases on the same device. Closing until further demonstration that this is still an issue.

**Closed by Zetaphor** 2016-01-28 18:56 UTC
Labels: bug
